import { ShieldPhase, ShieldLayer, ShieldModulator, ShieldEmitter, Threat, ThreatType, ThreatLevel, OffensiveSpike, ShieldContext, ShieldStatus } from "./types";
import type { CellularShield, CellType, WormholeShieldSignal, Blockchain } from "./types";
export declare const ShieldCore: {
    run(context: ShieldContext): ShieldStatus;
    status(): ShieldStatus;
    ensureShieldPhases(): ShieldLayer[];
    getLayer(phase: ShieldPhase): ShieldLayer | undefined;
    listLayers(): ShieldLayer[];
    listActiveLayers(): ShieldLayer[];
    rotateFrequencies(): void;
    createModulator(phase: ShieldPhase, modulationType: ShieldModulator["modulationType"], frequency: number, amplitude?: number): ShieldModulator;
    ensureDefaultModulators(): ShieldModulator[];
    createEmitter(phase: ShieldPhase, emissionType: ShieldEmitter["emissionType"], targetThreatTypes: ThreatType[], power?: number, range?: number): ShieldEmitter;
    ensureDefaultEmitters(): ShieldEmitter[];
    detectThreat(type: ThreatType, level: ThreatLevel, source?: string, target?: string, payload?: Record<string, any>): Threat;
    getThreat(id: string): Threat | undefined;
    listThreats(): Threat[];
    listRecentThreats(limit?: number): Threat[];
    blockThreat(id: string): boolean;
    analyzeThreat(threat: Threat): {
        shouldBlock: boolean;
        recommendedSpike?: string;
    };
    fireSpike(name: string, type: OffensiveSpike["type"], target: string, power?: number, meta?: Record<string, any>): OffensiveSpike;
    fireSpikeAtThreat(threat: Threat, spikeType?: OffensiveSpike["type"]): OffensiveSpike | null;
    listSpikes(): OffensiveSpike[];
    listRecentSpikes(limit?: number): OffensiveSpike[];
    createCellularShield(cellId: string, cellType: CellType, wormholeId?: string): CellularShield;
    getCellularShield(cellId: string): CellularShield | undefined;
    listCellularShields(): CellularShield[];
    updateCellularShieldIntegrity(cellId: string, integrity: number): boolean;
    propagateShieldViaWormhole(signalType: WormholeShieldSignal["signalType"], sourcePhase: ShieldPhase, payload: Record<string, any>, targetCells?: string[]): WormholeShieldSignal;
    getCellularShieldStats(): {
        totalCells: number;
        wormholeConnected: number;
        avgIntegrity: number;
        totalThreats: number;
        totalBlocked: number;
    };
    getRecentWormholeSignals(limit?: number): WormholeShieldSignal[];
    learnFromThreats(): import("./logic/shieldLearner").ThreatPattern[];
    predictThreatSeverity(threat: Threat): ThreatLevel;
    getThreatPatterns(): import("./logic/shieldLearner").ThreatPattern[];
    initializeCrossChainShield(blockchain: Blockchain, chainId: string): import("./logic/crossChainShield").CrossChainShield;
    syncCrossChainShields(): void;
    detectCrossChainThreat(blockchain: Blockchain, threatType: ThreatType, level: ThreatLevel, source?: string): Threat | null;
    listCrossChainShields(): import("./logic/crossChainShield").CrossChainShield[];
    getCrossChainShieldStats(): {
        totalChains: number;
        activeChains: number;
        avgIntegrity: number;
        totalThreats: number;
        totalBlocked: number;
    };
};
export * from "./types";
export * from "./src/risk";
export default ShieldCore;
