import { SignalThread, SpiderInsight, SpiderWebStatus, Fly, WebSensor, ThreadTemplate, ThreadPattern, FlyPattern, ThreadPriority } from "../types";
export declare const SpiderStore: {
    addThread(thread: SignalThread): SignalThread;
    updateThread(thread: SignalThread): SignalThread;
    getThread(id: string): SignalThread | undefined;
    listThreads(): SignalThread[];
    listThreadsByStatus(status: SignalThread["status"]): SignalThread[];
    listThreadsByPriority(priority: ThreadPriority): SignalThread[];
    catchFly(fly: Fly): Fly;
    getFly(id: string): Fly | undefined;
    listFlies(): Fly[];
    listUnprocessedFlies(): Fly[];
    listStickyFlies(): Fly[];
    markFlyProcessed(flyId: string, threadId?: string): boolean;
    addSensor(sensor: WebSensor): WebSensor;
    getSensor(id: string): WebSensor | undefined;
    updateSensor(sensor: WebSensor): WebSensor;
    listSensors(): WebSensor[];
    listActiveSensors(): WebSensor[];
    updateSensorCatchRate(sensorId: string, catchRate: number): boolean;
    addTemplate(template: ThreadTemplate): ThreadTemplate;
    getTemplate(id: string): ThreadTemplate | undefined;
    listTemplates(): ThreadTemplate[];
    updateTemplateUsage(templateId: string, success: boolean): boolean;
    addThreadPattern(pattern: ThreadPattern): ThreadPattern;
    getThreadPattern(id: string): ThreadPattern | undefined;
    listThreadPatterns(): ThreadPattern[];
    addFlyPattern(pattern: FlyPattern): FlyPattern;
    getFlyPattern(id: string): FlyPattern | undefined;
    listFlyPatterns(): FlyPattern[];
    addInsight(insight: SpiderInsight): SpiderInsight;
    listInsights(): SpiderInsight[];
    listRecentInsights(limit?: number): SpiderInsight[];
    setLastRunAt(ts: number | null): void;
    status(): SpiderWebStatus;
};
