import { LeadStage } from "../wolfpack-funding-core";
/**
 * Pattern learned from historical data
 */
export interface LearnedPattern {
    id: string;
    type: "lead_quality" | "email_effectiveness" | "timing" | "stage_progression" | "scoring_correlation";
    pattern: string;
    confidence: number;
    evidence: {
        sampleSize: number;
        successRate?: number;
        examples: string[];
    };
    createdAt: number;
    lastValidated: number;
}
/**
 * Insight generated by the analyst
 */
export interface AnalystInsight {
    id: string;
    type: "prediction" | "recommendation" | "warning" | "opportunity" | "pattern";
    severity: "low" | "medium" | "high" | "critical";
    title: string;
    description: string;
    relatedLeadIds?: string[];
    relatedQueueIds?: string[];
    confidence: number;
    actionable: boolean;
    suggestedAction?: string;
    createdAt: number;
}
/**
 * Prediction about a lead or outcome
 */
export interface LeadPrediction {
    leadId: string;
    predictedStage: LeadStage;
    probability: number;
    timeframe?: string;
    factors: string[];
    confidence: number;
}
/**
 * Email effectiveness analysis
 */
export interface EmailEffectiveness {
    queueItemId: string;
    leadId: string;
    predictedResponseRate: number;
    factors: {
        subjectLineScore?: number;
        bodyLengthScore?: number;
        timingScore?: number;
        personalizationScore?: number;
    };
    recommendations?: string[];
}
/**
 * Training metrics
 */
export interface TrainingMetrics {
    totalPatternsLearned: number;
    totalInsightsGenerated: number;
    accuracyScore?: number;
    lastTrainingRun: number | null;
    trainingCycles: number;
}
/**
 * Analyst context (dependencies)
 */
export interface WolfPackAnalystContext {
    wolfPackFundingCore?: any;
    neuralMesh?: any;
    narrativeField?: any;
}
/**
 * Analyst status
 */
export interface WolfPackAnalystStatus {
    lastRunAt: number | null;
    trainingMetrics: TrainingMetrics;
    activePatterns: LearnedPattern[];
    recentInsights: AnalystInsight[];
    predictions: LeadPrediction[];
    emailEffectiveness: EmailEffectiveness[];
}
