# Simplified Cloud Build for backend-only deployment
# Builds directly in GCP to avoid Windows context issues

steps:
  # Build Docker image directly from source
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.backend'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dreamnet-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dreamnet-backend:latest'
      - '.'

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/dreamnet-backend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dreamnet-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dreamnet-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'

images:
  - 'gcr.io/$PROJECT_ID/dreamnet-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/dreamnet-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'
