import { LearnedPattern, AnalystInsight, LeadPrediction, EmailEffectiveness, WolfPackAnalystStatus } from "../types";
export declare const AnalystStore: {
    upsertPattern(pattern: LearnedPattern): LearnedPattern;
    getPattern(id: string): LearnedPattern | undefined;
    listPatterns(): LearnedPattern[];
    listPatternsByType(type: LearnedPattern["type"]): LearnedPattern[];
    addInsight(insight: AnalystInsight): AnalystInsight;
    getInsight(id: string): AnalystInsight | undefined;
    listInsights(): AnalystInsight[];
    listRecentInsights(limit?: number): AnalystInsight[];
    upsertPrediction(prediction: LeadPrediction): LeadPrediction;
    getPrediction(leadId: string): LeadPrediction | undefined;
    listPredictions(): LeadPrediction[];
    upsertEmailEffectiveness(eff: EmailEffectiveness): EmailEffectiveness;
    getEmailEffectiveness(queueItemId: string): EmailEffectiveness | undefined;
    listEmailEffectiveness(): EmailEffectiveness[];
    incrementTrainingCycles(): void;
    setAccuracyScore(score: number | undefined): void;
    setLastRunAt(ts: number | null): void;
    status(): WolfPackAnalystStatus;
};
