apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dreamnet-cluster
  region: us-east-1
  version: "1.28"

iam:
  withOIDC: true

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: HighlyAvailable

nodeGroups:
  - name: standard-ng
    instanceType: t3.large
    desiredCapacity: 3
    minSize: 3
    maxSize: 10
    volumeSize: 50
    volumeType: gp3
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        awsLoadBalancerController: true
        cloudWatch: true
    labels:
      app: dreamnet
      tier: backend
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/dreamnet-cluster: "owned"

managedNodeGroups:
  - name: fargate-ng
    instanceTypes:
      - t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    labels:
      app: dreamnet
      tier: frontend

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

