/**
 * OHARA APP REGISTRY (AGGREGATED)
 * Auto-generated by scripts/fleet_manifestor.ts
 */
import { MiniAppConfig } from './types.js';

import { OHARA_SHARD_1 } from './shards/shard-1.js';
import { OHARA_SHARD_2 } from './shards/shard-2.js';
import { OHARA_SHARD_3 } from './shards/shard-3.js';
import { OHARA_SHARD_4 } from './shards/shard-4.js';
import { OHARA_SHARD_5 } from './shards/shard-5.js';

export const OHARA_APPS: MiniAppConfig[] = [
    ...OHARA_SHARD_1,
    ...OHARA_SHARD_2,
    ...OHARA_SHARD_3,
    ...OHARA_SHARD_4,
    ...OHARA_SHARD_5
];
