import fs from "node:fs/promises";
import path from "node:path";
import type { GraftModel, GraftProcessor, InstallResult } from "../types";

const banner = `/**
 * Auto-generated by the DreamNet Graft Engine.
 * Edit this file to customize the grafted UI component.
 */
`;

export class UIProcessor implements GraftProcessor {
  async install(graft: GraftModel): Promise<InstallResult> {
    const targetApp = (graft.metadata?.targetApp as string) ?? "dreamscope";
    const appRoot = path.resolve(process.cwd(), `apps/${targetApp}`);
    const filePath = path.resolve(process.cwd(), graft.path.replace(/^\//, ""));

    await fs.mkdir(path.dirname(filePath), { recursive: true });

    const componentName = graft.metadata?.componentName ?? graft.name.replace(/[^a-zA-Z0-9]/g, "");
    const contents = `${banner}
import React from "react";

export default function ${componentName}() {
  return (
    <div className="rounded-xl border border-dashed border-electric-cyan/40 p-6 text-electric-cyan">
      <h2 className="text-xl font-semibold">Grafted UI: ${graft.name}</h2>
      <p className="mt-2 text-sm text-gray-400">
        This panel was generated automatically by the Graft Engine. Customize it at {graft.path}.
      </p>
    </div>
  );
}
`;

    await fs.writeFile(filePath, contents, "utf8");

    return {
      ok: true,
      message: `UI component created at ${filePath}`,
      logs: [`Generated UI graft component ${componentName}`],
    };
  }
}


