"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UIProcessor = void 0;
const promises_1 = __importDefault(require("node:fs/promises"));
const node_path_1 = __importDefault(require("node:path"));
const banner = `/**
 * Auto-generated by the DreamNet Graft Engine.
 * Edit this file to customize the grafted UI component.
 */
`;
class UIProcessor {
    async install(graft) {
        const targetApp = graft.metadata?.targetApp ?? "dreamscope";
        const appRoot = node_path_1.default.resolve(process.cwd(), `apps/${targetApp}`);
        const filePath = node_path_1.default.resolve(process.cwd(), graft.path.replace(/^\//, ""));
        await promises_1.default.mkdir(node_path_1.default.dirname(filePath), { recursive: true });
        const componentName = graft.metadata?.componentName ?? graft.name.replace(/[^a-zA-Z0-9]/g, "");
        const contents = `${banner}
import React from "react";

export default function ${componentName}() {
  return (
    <div className="rounded-xl border border-dashed border-electric-cyan/40 p-6 text-electric-cyan">
      <h2 className="text-xl font-semibold">Grafted UI: ${graft.name}</h2>
      <p className="mt-2 text-sm text-gray-400">
        This panel was generated automatically by the Graft Engine. Customize it at {graft.path}.
      </p>
    </div>
  );
}
`;
        await promises_1.default.writeFile(filePath, contents, "utf8");
        return {
            ok: true,
            message: `UI component created at ${filePath}`,
            logs: [`Generated UI graft component ${componentName}`],
        };
    }
}
exports.UIProcessor = UIProcessor;
