import { FundingLead, SendQueueItem, LeadStage, LeadType } from "@dreamnet/wolfpack-funding-core";

/**
 * Pattern learned from historical data
 */
export interface LearnedPattern {
  id: string;
  type: "lead_quality" | "email_effectiveness" | "timing" | "stage_progression" | "scoring_correlation";
  pattern: string; // Human-readable description
  confidence: number; // 0-1
  evidence: {
    sampleSize: number;
    successRate?: number;
    examples: string[]; // Lead IDs or queue IDs that match this pattern
  };
  createdAt: number;
  lastValidated: number;
}

/**
 * Insight generated by the analyst
 */
export interface AnalystInsight {
  id: string;
  type: "prediction" | "recommendation" | "warning" | "opportunity" | "pattern";
  severity: "low" | "medium" | "high" | "critical";
  title: string;
  description: string;
  relatedLeadIds?: string[];
  relatedQueueIds?: string[];
  confidence: number; // 0-1
  actionable: boolean;
  suggestedAction?: string;
  createdAt: number;
}

/**
 * Prediction about a lead or outcome
 */
export interface LeadPrediction {
  leadId: string;
  predictedStage: LeadStage;
  probability: number; // 0-1
  timeframe?: string; // e.g., "within 7 days"
  factors: string[]; // What factors influenced this prediction
  confidence: number; // 0-1
}

/**
 * Email effectiveness analysis
 */
export interface EmailEffectiveness {
  queueItemId: string;
  leadId: string;
  predictedResponseRate: number; // 0-1
  factors: {
    subjectLineScore?: number;
    bodyLengthScore?: number;
    timingScore?: number;
    personalizationScore?: number;
  };
  recommendations?: string[];
}

/**
 * Training metrics
 */
export interface TrainingMetrics {
  totalPatternsLearned: number;
  totalInsightsGenerated: number;
  accuracyScore?: number; // How accurate predictions have been
  lastTrainingRun: number | null;
  trainingCycles: number;
}

/**
 * Analyst context (dependencies)
 */
export interface WolfPackAnalystContext {
  wolfPackFundingCore?: any; // WolfPackFundingCore
  neuralMesh?: any; // NeuralMesh for memory storage
  narrativeField?: any; // NarrativeField for logging
}

/**
 * Analyst status
 */
export interface WolfPackAnalystStatus {
  lastRunAt: number | null;
  trainingMetrics: TrainingMetrics;
  activePatterns: LearnedPattern[];
  recentInsights: AnalystInsight[];
  predictions: LeadPrediction[];
  emailEffectiveness: EmailEffectiveness[];
}

