
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Configuration
const FLEET_DATA_PATH = path.join(__dirname, '../packages/client/public/data/fleet.json');
const SHARDS_OUTPUT_DIR = path.join(__dirname, '../packages/client/src/miniapps/shards');
const REGISTRY_OUTPUT_PATH = path.join(__dirname, '../packages/client/src/miniapps/ohara-registry.ts');

const ITEMS_PER_SHARD = 20;

interface AppEntry {
    id: string;
    name: string;
    description: string;
    category: string;
}

async function manifestFleet() {
    console.log("🔱 DREAMNET FLEET MANIFESTOR");
    console.log("   Loading fleet data...");

    if (!fs.existsSync(FLEET_DATA_PATH)) {
        console.error(`❌ Fleet data missing: ${FLEET_DATA_PATH}`);
        console.error("   Run 'npx tsx scripts/extract_fleet.ts' first!");
        process.exit(1);
    }

    const rawData = fs.readFileSync(FLEET_DATA_PATH, 'utf-8');
    const apps: AppEntry[] = JSON.parse(rawData);

    console.log(`   Manifesting ${apps.length} sovereign entities...`);

    // Ensure output dir
    if (!fs.existsSync(SHARDS_OUTPUT_DIR)) {
        fs.mkdirSync(SHARDS_OUTPUT_DIR, { recursive: true });
    }

    // 1. Generate Shards
    let shardCount = 0;
    const shardImports: string[] = [];

    for (let i = 0; i < apps.length; i += ITEMS_PER_SHARD) {
        const chunk = apps.slice(i, i + ITEMS_PER_SHARD);
        shardCount++;
        const shardName = `shard-${shardCount}`;

        const shardContent = `/**
 * OHARA REGISTRY SHARD ${shardCount}
 * Auto-generated by scripts/fleet_manifestor.ts
 */
import { MiniAppConfig } from '../types.js';

export const OHARA_SHARD_${shardCount}: MiniAppConfig[] = [
${chunk.map(app => `  {
    id: '${app.id}',
    name: ${JSON.stringify(app.name)},
    description: ${JSON.stringify(app.description)},
    route: '/miniapps/ohara/${app.id}',
    category: '${app.category}',
    requiresWallet: true,
    version: '1.0.0',
    isConnected: false,
    chainId: 8453,
    connect: async () => {},
    disconnect: () => {},
    switchToBase: async () => {}
  }`).join(',\n')}
];
`;
        fs.writeFileSync(path.join(SHARDS_OUTPUT_DIR, `${shardName}.ts`), shardContent);
        console.log(`   ✨ Materialized ${shardName}.ts (${chunk.length} units)`);

        // Note the .js extension for the aggregator!
        shardImports.push(`import { OHARA_SHARD_${shardCount} } from './shards/${shardName}.js';`);
    }

    // 2. Generate Aggregator (Registry)
    const registryContent = `/**
 * OHARA APP REGISTRY (AGGREGATED)
 * Auto-generated by scripts/fleet_manifestor.ts
 */
import { MiniAppConfig } from './types.js';

${shardImports.join('\n')}

export const OHARA_APPS: MiniAppConfig[] = [
    ${shardImports.map((_, idx) => `...OHARA_SHARD_${idx + 1}`).join(',\n    ')}
];
`;

    fs.writeFileSync(REGISTRY_OUTPUT_PATH, registryContent);
    console.log(`✅ Fleet Manifest Complete. Registry Online.`);
    console.log(`   Target: ${REGISTRY_OUTPUT_PATH}`);
}

manifestFleet();
