#!/usr/bin/env tsx
import fs from 'fs';
import path from 'path';

const DUMP_PATH = path.join(process.cwd(), 'OHARA_DUMP.txt');
const REGISTRY_PATH = path.join(process.cwd(), 'packages/client/src/miniapps/ohara-registry.ts');

async function main() {
    console.log("🗑️  Processing Text Dump with Ticker Pivot...");

    if (!fs.existsSync(DUMP_PATH)) {
        console.error("❌ OHARA_DUMP.txt not found.");
        process.exit(1);
    }

    const content = fs.readFileSync(DUMP_PATH, 'utf-8');
    // Remove empty lines for easier processing
    const lines = content.split('\n').map(l => l.trim()).filter(l => l.length > 0);

    // Strategy: Look for lines starting with '$'.
    // The line BEFORE is the Name.
    // The line AFTER is usually view count or stats.

    interface ScrapedApp {
        name: string;
        ticker: string;
    }

    const apps: ScrapedApp[] = [];

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (line.startsWith('$') && line.length < 10 && /^[A-Z0-9$]+$/.test(line)) {
            // Found a ticker (e.g. $SOUL)
            const ticker = line;
            // Name should be at i-1
            const name = lines[i - 1];

            // Validate name isn't metadata like "1mo ago"
            if (name && !name.includes('ago') && !name.includes('Avatar')) {
                apps.push({ name, ticker });
            }
        }
    }

    console.log(`✅ Extracted ${apps.length} apps from text dump.`);

    const registryContent = `/**
 * OHARA APP REGISTRY
 * Auto-generated by scripts/ingest_ohara_dump.ts
 * Source: OHARA_DUMP.txt
 */

import { MiniAppConfig } from './types.js';

export const OHARA_APPS: MiniAppConfig[] = [
${apps.map((app, index) => {
        // Generate a deterministic slug for the ID until we have real UUIDs
        const slug = app.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

        return `  {
    id: '${slug}',
    name: "${app.name}",
    description: "Sovereign App (Ticker: ${app.ticker})",
    route: '/miniapps/ohara/${slug}',
    category: '${['DreamNet', 'Modu'].some(k => app.name.includes(k)) ? 'utility' : 'gaming'}', 
    requiresWallet: true,
    version: '1.0.0',
    isConnected: false,
    chainId: 8453,
    connect: async () => {},
    disconnect: () => {},
    switchToBase: async () => {}
  },`;
    }).join('\n')}
];
`;

    fs.writeFileSync(REGISTRY_PATH, registryContent);
    console.log(`✅ Registry Updated: ${REGISTRY_PATH}`);
}

main().catch(console.error);
