#!/usr/bin/env tsx
/**
 * 🚀 Sovereign Fleet Linker (formerly Mass Migration)
 * 
 * Capability: Reads OHARA_APP_LIST.md, validates App IDs, and
 * generates key/client/src/miniapps/ohara-registry.ts to publish 
 * the fleet to DreamNet.
 */

import fs from 'fs';
import path from 'path';

// Paths
const MARKDOWN_PATH = path.join(process.cwd(), 'OHARA_APP_LIST.md');
const REGISTRY_PATH = path.join(process.cwd(), 'packages/client/src/miniapps/ohara-registry.ts');

interface OharaAppEntry {
    name: string;
    id: string; // The UUID
    description: string;
    category: string;
}

async function main() {
    console.log("🔱 INITIATING SOVEREIGN FLEET LINK...");
    console.log(`   Reading manifest: ${MARKDOWN_PATH}`);

    if (!fs.existsSync(MARKDOWN_PATH)) {
        console.error("❌ OHARA_APP_LIST.md not found!");
        process.exit(1);
    }

    const content = fs.readFileSync(MARKDOWN_PATH, 'utf-8');
    const lines = content.split('\n');

    const apps: OharaAppEntry[] = [];
    let currentCategory = 'other';

    // Regex to find "1. **Name**" or "1. **Name** (ID: ...)"
    const itemRegex = /^\d+\.\s+\*\*(.*?)\*\*/;
    const idRegex = /\(ID:\s*([a-zA-Z0-9-]+)\)/i;
    const descRegex = /^\s*\*\s*\*Function\*:\s*(.*)/;

    let pendingApp: Partial<OharaAppEntry> | null = null;

    for (const line of lines) {
        // Detect Category
        if (line.includes('Category A:')) currentCategory = 'core';
        if (line.includes('Category B:')) currentCategory = 'ecosystem';

        // Detect App Item
        const itemMatch = line.match(itemRegex);
        if (itemMatch) {
            // Save previous if exists
            if (pendingApp && pendingApp.name && pendingApp.id) {
                apps.push(pendingApp as OharaAppEntry);
            } else if (pendingApp && pendingApp.name) {
                console.warn(`⚠️  Missing ID for: ${pendingApp.name}`);
            }

            const name = itemMatch[1];
            // Try to find ID in the SAME line or check if validation is needed
            const idMatch = line.match(idRegex);
            const id = idMatch ? idMatch[1] : `PENDING_ID_${name.replace(/\s+/g, '_').toUpperCase()}`;

            pendingApp = {
                name,
                id,
                category: currentCategory,
                description: 'Sovereign Ohara App' // Default
            };

            if (!idMatch) {
                console.log(`   🔸 Found App: ${name} (Waiting for ID...)`);
            } else {
                console.log(`   ✅ Linked App: ${name} (${id})`);
            }
        }

        // Detect Function/Description
        const descMatch = line.match(descRegex);
        if (descMatch && pendingApp) {
            pendingApp.description = descMatch[1];
        }
    }

    // Push last one
    if (pendingApp && pendingApp.name) {
        apps.push(pendingApp as OharaAppEntry);
    }

    // GENERATE REGISTRY CONTENT
    console.log(`\n📝 Generating Registry for ${apps.length} apps...`);

    const registryContent = `/**
 * OHARA APP REGISTRY
 * Auto-generated by scripts/mass_migrate_fleet.ts
 * Source: OHARA_APP_LIST.md
 */

import { MiniAppConfig } from './types.js';

export const OHARA_APPS: MiniAppConfig[] = [
${apps.map(app => `  {
    id: '${app.id}',
    name: "${app.name}",
    description: "${app.description}",
    route: '/miniapps/ohara/${app.id}',
    category: '${app.category === 'core' ? 'utility' : 'gaming'}', // Simplified mapping based on Ohara types
    requiresWallet: true,
    version: '1.0.0',
    isConnected: false,
    chainId: 8453,
    connect: async () => {},
    disconnect: () => {},
    switchToBase: async () => {}
  },`).join('\n')}
];
`;

    fs.writeFileSync(REGISTRY_PATH, registryContent);
    console.log(`✅ Registry Updated: ${REGISTRY_PATH}`);
    console.log(`\n⚠️  ACTION REQUIRED: Edit OHARA_APP_LIST.md to include named IDs in format:`);
    console.log(`   1. **AppName** (ID: 123-456-789)`);
}

main().catch(console.error);
