#!/usr/bin/env tsx
/**
 * 🧹 SifterAgent: Metabolic Waste Nutrient Extraction
 * Scans build logs for error patterns and extracts "Innovation Seeds".
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Common Error Patterns to Sift
const PATTERNS = [
    { id: "ERR_MODULE_NOT_FOUND", regex: /ERR_MODULE_NOT_FOUND/g, priority: "HIGH" },
    { id: "ERR_INVALID_THIS", regex: /ERR_INVALID_THIS/g, priority: "CRITICAL" },
    { id: "PNPM_LOCKED", regex: /ERR_PNPM_LOCKFILE_OUT_OF_DATE/g, priority: "MEDIUM" },
    { id: "TS_AST_CONFLICT", regex: /can have at most one '\*' character/g, priority: "HIGH" }
];

async function siftLogs(logFilePath: string) {
    if (!existsSync(logFilePath)) {
        console.error(`❌ Log file not found: ${logFilePath}`);
        return;
    }

    const content = readFileSync(logFilePath, "utf-8");
    const seeds: any[] = [];

    console.log("🕵️ Sifting through metabolic waste...");

    PATTERNS.forEach(pattern => {
        const matches = content.match(pattern.regex);
        if (matches) {
            console.log(`✨ Found ${matches.length} instances of ${pattern.id} (${pattern.priority})`);
            seeds.push({
                patternId: pattern.id,
                count: matches.length,
                priority: pattern.priority,
                timestamp: new Date().toISOString()
            });
        }
    });

    // Generate the report
    const reportPath = join(process.cwd(), "wisdom", "SIFTER_REPORT.md");
    const reportContent = `
# 🧹 SifterAgent Report: Metabolic Innovation Seeds

**Extracted at**: ${new Date().toLocaleString()}

## 🧪 Mutation Seeds (Detected Errors)

${seeds.map(s => `- **[${s.priority}]** \`${s.patternId}\`: Found ${s.count} times.`).join("\n")}

## 💡 Fix Blueprints

${seeds.some(s => s.patternId === "ERR_INVALID_THIS") ? "### 🔧 Fix: Vercel Node Runtime Conflict\n- **Status**: Critical\n- **Action**: Pin Node.js to 18.x and pnpm to 9.x in \`package.json\`. Set \`node-linker=hoisted\` in \`.npmrc\`." : ""}
${seeds.some(s => s.patternId === "TS_AST_CONFLICT") ? "### 🔧 Fix: TS Config Path Mapping\n- **Status**: Resolved\n- **Action**: Corrected \`tsconfig.base.json\` to remove multiple asterisks from path substitutions." : ""}

---
*Generated by SifterAgent. Metabolized from build entropy.*
`;

    writeFileSync(reportPath, reportContent);
    console.log(`✅ Sifter Report saved to ${reportPath}`);
}

// If run directly
const isMain = process.argv[1]?.endsWith('sifter-agent.ts') || process.argv[1]?.endsWith('sifter-agent.js');
if (isMain) {
    const logFile = process.argv[2] || "script_output.log";
    siftLogs(logFile).catch(console.error);
}

export { siftLogs };
