
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REGISTRY_PATH = path.join(__dirname, '../packages/client/src/miniapps/ohara-registry.ts');
const OUTPUT_DIR = path.join(__dirname, '../packages/client/src/miniapps/shards');

// Create shards directory
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

const content = fs.readFileSync(REGISTRY_PATH, 'utf-8');

// Primitive Regex Extraction because we don't want to deal with AST in a quick script
// Matches objects inside the array: { ... }
const objectRegex = /{\s+id:[\s\S]*?switchToBase: async \(\) => {}\s+}/g;
const matches = content.match(objectRegex);

if (!matches) {
    console.error("No apps found!");
    process.exit(1);
}

console.log(`Found ${matches.length} apps. Splitting into shards...`);

const CHUNK_SIZE = 20;
let shardCount = 0;

const shardImports: string[] = [];

for (let i = 0; i < matches.length; i += CHUNK_SIZE) {
    const chunk = matches.slice(i, i + CHUNK_SIZE);
    shardCount++;
    const shardName = `shard-${shardCount}`;
    const shardContent = `/**
 * OHARA REGISTRY SHARD ${shardCount}
 * Auto-generated by scripts/split_ohara_registry.ts
 */
import { MiniAppConfig } from '../types.js';

export const OHARA_SHARD_${shardCount}: MiniAppConfig[] = [
${chunk.join(',\n')}
];
`;

    fs.writeFileSync(path.join(OUTPUT_DIR, `${shardName}.ts`), shardContent);
    console.log(`Created ${shardName}.ts with ${chunk.length} apps.`);
    shardImports.push(`import { OHARA_SHARD_${shardCount} } from './shards/${shardName}.js';`);
}

// Generate Main Registry that aggregates shards
const mainRegistryContent = `/**
 * OHARA APP REGISTRY (AGGREGATED)
 * Auto-generated by scripts/split_ohara_registry.ts
 */
import { MiniAppConfig } from './types.js';

${shardImports.join('\n')}

export const OHARA_APPS: MiniAppConfig[] = [
    ${shardImports.map((_, idx) => `...OHARA_SHARD_${idx + 1}`).join(',\n    ')}
];
`;

fs.writeFileSync(REGISTRY_PATH, mainRegistryContent);
console.log(`Detailed ohara-registry.ts updated to aggregate ${shardCount} shards.`);
