/**
 * Pulse Dispatch: VDS Enhancement Brief
 * 
 * Dispatches the VDS Upgrade Report and Integration Plan to Keith and Brandon.
 * Run with: pnpm exec tsx scripts/dispatch-vds-brief.ts
 */

import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';

// Load env
const rootDir = 'C:/Users/brand/OneDrive/Documents/GitHub/dream-net';
dotenv.config({ path: path.join(rootDir, '.env') });

async function dispatchAnalysis() {
    console.log("📨 [Dispatch] Preparing VDS Enhancement Pulse...");

    try {
        const { dreamNetEmail } = await import('../src/email/DreamNetEmail.js');

        // Explicitly override configuration to use brandonducar1234
        dreamNetEmail.configure({
            provider: 'smtp',
            from: 'brandonducar1234@gmail.com',
            fromName: 'DreamNet Intelligence Service',
            smtpHost: 'smtp.gmail.com',
            smtpPort: 465,
            smtpSecure: true,
            smtpUser: 'brandonducar1234@gmail.com',
            smtpPass: 'xjqsrfjpnsrkeukl' // App Password from .env
        });

        const artifactsDir = 'C:/Users/brand/.gemini/antigravity/brain/24de7fd9-398f-46cc-820a-a0c989859b37';
        const reportPath = path.join(artifactsDir, 'VDS_SYSTEMS_UPGRADE_REPORT.md');
        const planPath = path.join(artifactsDir, 'implementation_plan_vds_integration.md');

        if (!fs.existsSync(reportPath)) throw new Error(`Report not found at ${reportPath}`);
        if (!fs.existsSync(planPath)) throw new Error(`Plan not found at ${planPath}`);

        const reportContent = fs.readFileSync(reportPath, 'utf8');
        const planContent = fs.readFileSync(planPath, 'utf8');

        const emailBody = `
# DREAMNET INTELLIGENCE BRIEF: VDS SYSTEMS EVOLUTION

Greetings,

The DreamNet Swarm has completed its analysis of the **Visual Data Solutions (VDS)** ecosystem. 

We are shifting our focus from simple data retrieval to **System Evolution**. Below are our strategic suggestions for upgrading PerfectPass into a proactive behavioral intelligence platform.

---

${reportContent}

---

## INTEGRATION & ENHANCEMENT PLAN

${planContent}

---

**Sovereign Directive**: Support the system. Evolve the workflow.

*Generated by DreamNet Cortex 2.0*
        `;

        const recipients = ['keith@franklinkeith.com', 'brandonducar1234@gmail.com'];

        for (const to of recipients) {
            console.log(`📤 Sending pulse to: ${to}...`);
            const result = await dreamNetEmail.sendEmail(
                to,
                'DREAMNET BRIEF: VDS Systems Upgrade & Integration Strategy 🛰️🧬🩸',
                emailBody
            );

            if (result.status === 'sent') {
                console.log(`✅ Dispatch Successful to ${to}. ID: ${result.id}`);
            } else {
                console.error(`❌ Dispatch Failed to ${to}: ${result.error}`);
            }
        }

    } catch (error: any) {
        console.error("💥 Dispatch Failed:", error.message);
        process.exit(1);
    }
}

dispatchAnalysis();
