import { SEOOptimization, SEOKeyword, Geofence, GeofenceRule, SEOInsight, AISEOCoreStatus } from "../types";
export declare const SEOStore: {
    addOptimization(optimization: SEOOptimization): SEOOptimization;
    getOptimization(id: string): SEOOptimization | undefined;
    listOptimizations(): SEOOptimization[];
    addKeyword(keyword: SEOKeyword): SEOKeyword;
    getKeyword(keyword: string): SEOKeyword | undefined;
    listKeywords(): SEOKeyword[];
    getTopKeywords(limit?: number): SEOKeyword[];
    addGeofence(geofence: Geofence): Geofence;
    getGeofence(id: string): Geofence | undefined;
    listGeofences(): Geofence[];
    listActiveGeofences(): Geofence[];
    addGeofenceRule(rule: GeofenceRule): GeofenceRule;
    getGeofenceRule(id: string): GeofenceRule | undefined;
    listGeofenceRules(): GeofenceRule[];
    listRulesForGeofence(geofenceId: string): GeofenceRule[];
    addInsight(insight: SEOInsight): SEOInsight;
    listInsights(): SEOInsight[];
    listRecentInsights(limit?: number): SEOInsight[];
    setLastRunAt(ts: number | null): void;
    status(): AISEOCoreStatus;
};
