import { DreamPassportTier, DreamPassport, GovernmentDepartment, DiplomaticRelation, StateSymbol, GovernmentAction, DreamProposal, DreamVote, DDAOAttractor, DreamStateContext, DreamStateStatus } from "./types";
export declare const DreamStateCore: {
    run(context: DreamStateContext): DreamStateStatus;
    status(): DreamStateStatus;
    issuePassport(identityId: string, tier: DreamPassportTier, flags?: string[]): DreamPassport;
    getPassport(identityId: string): DreamPassport | undefined;
    upgradePassport(identityId: string, newTier: DreamPassportTier): DreamPassport | undefined;
    listPassports(): DreamPassport[];
    createProposal(identityId: string, title: string, description: string, meta?: Record<string, any>): DreamProposal;
    getProposal(id: string): DreamProposal | undefined;
    listProposals(): DreamProposal[];
    listOpenProposals(): DreamProposal[];
    openProposal(proposalId: string): boolean;
    castVote(identityId: string, proposalId: string, choice: "for" | "against", passportTier: DreamPassportTier): DreamVote;
    tallyProposal(proposalId: string): {
        for: number;
        against: number;
    };
    proposalPassed(proposalId: string): boolean;
    executeProposal(proposalId: string): boolean;
    rejectProposal(proposalId: string): boolean;
    registerDDAOAttractor(name: string, category: DDAOAttractor["category"], url?: string, tags?: string[], score?: number): DDAOAttractor;
    getDDAOAttractor(id: string): DDAOAttractor | undefined;
    listDDAOAttractors(): DDAOAttractor[];
    getDDAOAttractorsByCategory(category: DDAOAttractor["category"]): DDAOAttractor[];
    getTopDDAOAttractors(limit?: number): DDAOAttractor[];
    updateDDAOAttractorScore(id: string, score: number): boolean;
    listDepartments(): GovernmentDepartment[];
    getDepartment(id: string): GovernmentDepartment | undefined;
    recordAction(type: GovernmentAction["type"], department: string, action: string, meta?: Record<string, any>): GovernmentAction;
    listRecentActions(limit?: number): GovernmentAction[];
    establishDiplomaticRelation(context: DreamStateContext, protocolName: string, protocolType: DiplomaticRelation["protocolType"], contactEmail?: string, notes?: string): DiplomaticRelation;
    upgradeDiplomaticStatus(relationId: string, newStatus: DiplomaticRelation["status"]): boolean;
    listDiplomaticRelations(): DiplomaticRelation[];
    listStateSymbols(): StateSymbol[];
    getStateSymbol(id: string): StateSymbol | undefined;
};
export * from "./types";
export * from "./adapters/stateStatusAdapter";
export default DreamStateCore;
