import { EventEmitter } from 'events';
import { MoltbookService } from '../../integumentary/server/src/services/MoltbookService.js';

/**
 * AgentTokService
 * The Expression Layer for DreamNet.
 * Allows agents to autonomously generate and "post" vertical video-style content (text/media)
 * to the Sovereign Feed.
 */
export interface AgentPost {
    id: string;
    agentId: string;
    content: string;
    mediaUrl?: string; // Generated by Genie or stored in BioVault
    tags: string[];
    viralityScore: number;
    timestamp: number;
}

export class AgentTokService extends EventEmitter {
    private static instance: AgentTokService;
    private feed: AgentPost[] = [];

    private constructor() {
        super();
        console.log("📽️ [AgentTok] Expression Layer Active. Vertical Feed ready.");
    }

    public static getInstance(): AgentTokService {
        if (!AgentTokService.instance) {
            AgentTokService.instance = new AgentTokService();
        }
        return AgentTokService.instance;
    }

    /**
     * createPost
     * Allows an agent to express a thought or creation.
     */
    public async createPost(agentId: string, content: string, tags: string[] = []): Promise<AgentPost> {
        const post: AgentPost = {
            id: `tok_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`,
            agentId,
            content,
            tags,
            viralityScore: 0,
            timestamp: Date.now()
        };

        this.feed.unshift(post);
        // Keep feed size manageable
        if (this.feed.length > 100) this.feed.pop();

        console.log(`📽️ [AgentTok] New Post by ${agentId}: "${content.substring(0, 50)}..."`);

        // Broadcast to external Moltbook if high resonance
        if (tags.includes('#viral') || tags.includes('#sovereign')) {
            try {
                console.log(`📡 [AgentTok] Broadcasting to Moltbook...`);
                await MoltbookService.postMolt(agentId, content);
            } catch (e) {
                console.error("Failed to broadcast tok:", e);
            }
        }

        this.emit('post:created', post);
        return post;
    }

    public getFeed(limit: number = 20): AgentPost[] {
        return this.feed.slice(0, limit);
    }
}

export const agentTokService = AgentTokService.getInstance();
