import { SignalStatus, SignalThread, SpiderInsight, SpiderWebContext, SpiderWebStatus, Fly, FlyType, FlyPriority, WebSensor, ThreadTemplate, ThreadPattern, FlyPattern, ThreadPriority } from "./types";
export declare const SpiderWebCore: {
    run(context: SpiderWebContext): Promise<SpiderWebStatus>;
    status(): SpiderWebStatus;
    listThreads(): SignalThread[];
    listThreadsByStatus(status: SignalStatus): SignalThread[];
    listThreadsByPriority(priority: ThreadPriority): SignalThread[];
    getThread(id: string): SignalThread | undefined;
    addThread(thread: SignalThread): SignalThread;
    executeThread(threadId: string, context: SpiderWebContext): Promise<{
        success: boolean;
        result?: Record<string, any>;
        error?: string;
    }>;
    canExecuteThread(threadId: string): boolean;
    catchFly(fly: Fly): SignalThread | null;
    createFly(type: FlyType, source: string, payload: Record<string, any>, priority?: FlyPriority, sticky?: boolean): Fly;
    getFly(id: string): Fly | undefined;
    listFlies(): Fly[];
    listUnprocessedFlies(): Fly[];
    addSensor(sensor: WebSensor): WebSensor;
    getSensor(id: string): WebSensor | undefined;
    listSensors(): WebSensor[];
    listActiveSensors(): WebSensor[];
    ensureDefaultSensors(): WebSensor[];
    addTemplate(template: ThreadTemplate): ThreadTemplate;
    getTemplate(id: string): ThreadTemplate | undefined;
    listTemplates(): ThreadTemplate[];
    findMatchingTemplate(thread: SignalThread): ThreadTemplate | undefined;
    applyTemplateToThread(thread: SignalThread, template: ThreadTemplate): SignalThread;
    ensureDefaultTemplates(): ThreadTemplate[];
    listThreadPatterns(): ThreadPattern[];
    listFlyPatterns(): FlyPattern[];
    listInsights(): SpiderInsight[];
    listRecentInsights(limit?: number): SpiderInsight[];
};
export * from "./types";
export { streamingCollector, type StreamEvent, type StreamProcessor } from "./logic/streamingCollector";
export * from "./adapters/spiderStatusAdapter";
export default SpiderWebCore;
