/**
 * Agent Gateway Tool Registry
 * Defines available tools and their access requirements
 */
export const TOOL_REGISTRY = {
    "env.get": {
        id: "env.get",
        label: "Get environment variable",
        description: "Read an environment variable (redacted where needed).",
        clusterId: "ENVKEEPER_CORE",
        portId: "ENVKEEPER_PORT",
        minTier: "OPERATOR",
        requiredCabinetIds: ["DATA_PRIVACY_CABINET"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0 },
        riskLevel: "medium",
    },
    "env.set": {
        id: "env.set",
        label: "Set environment variable",
        description: "Create or update an env var via Env Keeper.",
        clusterId: "ENVKEEPER_CORE",
        portId: "ENVKEEPER_PORT",
        minTier: "OPERATOR",
        requiredCabinetIds: ["DATA_PRIVACY_CABINET"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0 },
        riskLevel: "high",
    },
    "env.delete": {
        id: "env.delete",
        label: "Delete environment variable",
        description: "Delete an environment variable via Env Keeper.",
        clusterId: "ENVKEEPER_CORE",
        portId: "ENVKEEPER_PORT",
        minTier: "OPERATOR",
        requiredCabinetIds: ["DATA_PRIVACY_CABINET"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0 },
        riskLevel: "high",
    },
    "api.listKeys": {
        id: "api.listKeys",
        label: "List API keys",
        description: "List all API keys managed by API Keeper.",
        clusterId: "API_KEEPER",
        portId: "APIKEEPER_PORT",
        minTier: "OPERATOR",
        requiredCabinetIds: ["TREASURY_CABINET"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0 },
        riskLevel: "high",
    },
    "api.rotateKey": {
        id: "api.rotateKey",
        label: "Rotate API key",
        description: "Rotate an API key (generate new, deprecate old).",
        clusterId: "API_KEEPER",
        portId: "APIKEEPER_PORT",
        minTier: "OPERATOR",
        requiredCabinetIds: ["TREASURY_CABINET"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0 },
        riskLevel: "critical",
    },
    "vercel.deploy": {
        id: "vercel.deploy",
        label: "Trigger Vercel deployment",
        description: "Trigger a Vercel deployment for a project.",
        clusterId: "DEPLOYKEEPER_CORE",
        portId: "VERCEL_PORT",
        minTier: "OPERATOR",
        requiredOfficeIds: ["FOUNDER", "MINISTER_OF_WOLF_OPERATIONS"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0.02 },
        riskLevel: "high",
    },
    "vercel.listProjects": {
        id: "vercel.listProjects",
        label: "List Vercel projects",
        description: "List all Vercel projects tracked by Vercel Agent.",
        clusterId: "DEPLOYKEEPER_CORE",
        portId: "VERCEL_PORT",
        minTier: "BUILDER",
        requiredOfficeIds: ["FOUNDER", "MINISTER_OF_WOLF_OPERATIONS"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0 },
        riskLevel: "medium",
    },
    "cloudrun.deploy": {
        id: "cloudrun.deploy",
        label: "Deploy to Cloud Run",
        description: "Deploy a service to Google Cloud Run with specified configuration.",
        clusterId: "CLOUD_RUN_CORE",
        portId: "CLOUD_RUN_PORT",
        minTier: "OPERATOR",
        requiredOfficeIds: ["FOUNDER", "MINISTER_OF_WOLF_OPERATIONS"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0.05 },
        riskLevel: "critical",
    },
    "cloudrun.scale": {
        id: "cloudrun.scale",
        label: "Scale Cloud Run service",
        description: "Update min/max instances for a Cloud Run service (governed by budget).",
        clusterId: "CLOUD_RUN_CORE",
        portId: "CLOUD_RUN_PORT",
        minTier: "OPERATOR",
        requiredOfficeIds: ["FOUNDER", "MINISTER_OF_WOLF_OPERATIONS"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0.01 },
        riskLevel: "high",
    },
    "cloudrun.update": {
        id: "cloudrun.update",
        label: "Update Cloud Run service",
        description: "Update environment variables, resources, or other Cloud Run service settings.",
        clusterId: "CLOUD_RUN_CORE",
        portId: "CLOUD_RUN_PORT",
        minTier: "OPERATOR",
        requiredOfficeIds: ["FOUNDER", "MINISTER_OF_WOLF_OPERATIONS"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0.02 },
        riskLevel: "high",
    },
    "cloudrun.list": {
        id: "cloudrun.list",
        label: "List Cloud Run services",
        description: "List all Cloud Run services in the project.",
        clusterId: "CLOUD_RUN_CORE",
        portId: "CLOUD_RUN_PORT",
        minTier: "OPERATOR",
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0 },
        riskLevel: "medium",
    },
    "cloudrun.getStatus": {
        id: "cloudrun.getStatus",
        label: "Get Cloud Run service status",
        description: "Get current status, health, and configuration of a Cloud Run service.",
        clusterId: "CLOUD_RUN_CORE",
        portId: "CLOUD_RUN_PORT",
        minTier: "OPERATOR",
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0 },
        riskLevel: "low",
    },
    "cloudrun.setKeepAlive": {
        id: "cloudrun.setKeepAlive",
        label: "Set Cloud Run keep-alive",
        description: "Configure minInstances to prevent scale-to-zero (governed by budget).",
        clusterId: "CLOUD_RUN_CORE",
        portId: "CLOUD_RUN_PORT",
        minTier: "OPERATOR",
        requiredOfficeIds: ["FOUNDER", "MINISTER_OF_WOLF_OPERATIONS"],
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0.01 },
        riskLevel: "high",
    },
    "diagnostics.ping": {
        id: "diagnostics.ping",
        label: "Ping DreamNet core",
        description: "Basic connectivity check to DreamNet core systems.",
        clusterId: "DREAM_STATE", // Using DREAM_STATE as placeholder for core diagnostics
        portId: "AGENT_GATEWAY",
        minTier: "SEED",
        cost: { estimatedTokenCost: 0, estimatedDollarCost: 0 },
        riskLevel: "low",
    },
};
export function getToolConfig(id) {
    return TOOL_REGISTRY[id];
}
export function listTools() {
    return Object.values(TOOL_REGISTRY);
}
